# Generated by Django 3.2.4 on 2021-07-23 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_libro', to='libro.categoria'),
        ),
    ]
