# Generated by Django 3.2.4 on 2021-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Autor name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Autor last name')),
                ('nationality', models.CharField(max_length=30, verbose_name='Autor nationality')),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
    ]
