# Generated by Django 3.2.4 on 2021-07-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_alter_libro_category'),
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Reader last name'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_prestamo', to='libro.libro'),
        ),
    ]
